### ISSUE TITLE
Drop-down menus overlaping pie in Settings - Menu

### ISSUE THREAD

**Issue by J0n1k4** [ngdeleito/easyGestures#14]
Hi,
thank you for this highly configurable add on. 
It works great.
A minor visual inconvenience (not really an issue) - at settings page, menus, the drop-down menus for selecting actions are overlapping the pie menu:
[https://postimg.cc/ppfpQ6rm](https://postimg.cc/ppfpQ6rm)

Thaks again for great add-on,
cheers

**Comment by ngdeleito** [comment]
Thanks for the comment and for reporting the problem! I noticed it recently and already fixed it (https://github.com/ngdeleito/easyGestures/commit/be17425eb0fa2dbc54101cb33d2fa94bafeda285). I just need to issue a new version of the extension, which I hope to be able to do soon.
