### ISSUE TITLE
Scripts, again

### ISSUE THREAD

**Issue by J0n1k4** [ngdeleito/easyGestures#15]
Hi,

I was looking at 

[https://github.com/ngdeleito/easyGestures/issues/4](https://github.com/ngdeleito/easyGestures/issues/4)

and I realize that it is not so easy to implement some script. However - I thought to ask if it is even possible, so I would know weather to spend some time investigating how to accomplish it or I shouldn't even try.
(I use the RMB click for opening pie menu. This way I can open the menu from track-pad as well when I am not using the mouse so there is no middle button available)

- I wonder if it is possible to assign the default right mouse context menu to an action within pie?
The Ctrl + Right click is one way to do it, but is it possible to do it with the Pie action without the other hand involved (for example RMB+ Swipe right)?

One of the things I often use is a spell check and the suggestions that FF gives if I misspell the word (it is underlined red, and in context menu there are suggestions for correction). It would be more convenient if I could have the ability to see and chose the correct word without using the other hand.
 
-  I have a few add-ons for FF, including 
------ "Save Page WE" (I see that it has a configurable keyboard shortcuts, so if F2 can be assigned to the Script, I suppose that Alt+A or what ever I assign to triger Save Page WE can also be assigned?)
------ "Save Text to File" (Extremely convenient to save selected text in TXT format, including the link to the web-page the text was saved from - Keyboard shortcut, Ctrl+Shift+Y)
------ "Save As PDF" - I suppose that I can find an extension that have a keyboard shortcut for this purpose, if it matters...
------ "Save In…" - Adds a context menu to save media {image, video, audio, link, selection, page} in user-defined folders or directories relative to the default download location. Not so often, but sometimes I have a need to save multiple files to predefined folders. It would be more convenient to assign this add-on to a Pie - gesture...

If it is possible. 

Thanks again for the great add-on,
cheers

FF.77.0.1. (64bit) on Win 10

**Comment by ngdeleito** [comment]
Hi,

> I wonder if it is possible to assign the default right mouse context menu to an action within pie?

As far as I know, it is not possible, unfortunately. Events created programmatically (like the solution in https://github.com/ngdeleito/easyGestures/issues/4) generate "untrusted" events nowadays, which cannot be used to open e.g. the context menu.

If I correctly understand the rest of your question, you would like to use the same approach (generating keystroke events programmatically) to run specific actions offered by other extensions. The answer here is the same as above. I would also be interested in such a possibility, but unfortunately I haven't found any appropriate solution to it.

Hope this answers all your questions. Do not hesitate to further comment if not.

**Comment by J0n1k4** [comment]
Ok, thank you for the answer. And once again - thank you for the wonderful add-on.
Cheers,
Nika
