### ISSUE TITLE
[Feature request]Restore toggle on/off ability

### ISSUE THREAD

**Issue by cchris005** [ngdeleito/easyGestures#2]
Hi, and thank you for sparing us users the updating of the .rdf file! 

I'm a longtime user of easyGestures and was quite happy to know about this revived version. One small glitch is that I had to enter all customisations again, but it's ok, you have to do this only once after all.
The matter at hand is that EG4.3.2 used to show a toggle icon on the add-on bar (or wherever) to toggle it at times where you need to get control back on various mouse clicks. I couldn't find it any longer (FF31 ESR  here on Win7 pro 64). The feature request is to simply restore this functionality - or to document where it has gone, if it is still here. 
Keep up the good work!
CChris

**Comment by ngdeleito** [comment]
Hi CChris,

Thank you for your comment!

I removed the toggle icon when the status bar and the add-on bar were removed from Firefox and when I turned easyGestures into a restartless extension. The easiest is to disable the extension when you do not need it from the add-ons manager. Hope this works for you.

Best regards,
Nicolas
