### ISSUE TITLE
Back Site

### ISSUE THREAD

**Issue by seenab** [ngdeleito/easyGestures#7]
No longer working on version 5.1, Linux Mint 17,3, Firefox 51.0.1 (64 bit)

**Comment by ngdeleito** [comment]
Thanks for reporting! Indeed, I already noticed that backSite, forwardSite and lastPage actions (all of them make us of gBrowser.sessionHistory) stopped working on recent versions of Firefox. Hope to fix this soon.

Nicolas

**Comment by ngdeleito** [comment]
Unless I have overlooked it, it seems that the back site, first page, forward site and last page actions cannot be implemented in a WebExtension. Unfortunately, these actions will not be available in the next version of the extension and will eventually disappear. Very disappointing, I know.
