### ISSUE TITLE
Allow actions to be activated only by held button

### ISSUE THREAD

**Issue by MikeFHay** [ngdeleito/easyGestures#8]
All three standard mouse buttons already have a meaning when clicked. Currently easyGestures overrides those meanings. It would be nice to be able to configure easyGestures to only activate when a button is held, not clicked, so the mouse buttons can retain their existing use while also supporting gestures.

Thanks for making this add-on :)

**Comment by ngdeleito** [comment]
Thank you for your message!

The pie menu opens as soon as the chosen button is pressed (no need to release it, and hence no need to perform a click to open the menu). Moving then the pointer over the action to execute and releasing the button, closes the menu and executes the action ;-)

Clicking involves a mousedown event, so with your suggestion the pie menu would be opened at every click, unfortunately.
